# -*- coding: utf-8 -*-
import json

# ============================================================
# DONNEES REELLES extraites des annuaires officiels USTHB
# ============================================================

# Grade normalization
def g(code):
    m = {'PROF':'Professeur','PR':'Professeur','MCA':'MaEtre de ConfErences A',
         'MCB':'MaEtre de ConfErences B','MAA':'MaEtre Assistant A',
         'MAB':'MaEtre Assistant B','MABS':'MaEtre Assistant B'}
    return m.get(code.strip().upper(), code)

# ---- FACULTE DE MATHEMATIQUES ----
# Dept AlgEbre et ThEorie des Nombres (extrait de fmath.usthb.dz)
alg = [
    ("Brahim","ABBACI","MCA","brahim.abbaci@gmail.com"),
    ("Mourad","ABCHICHE","MCB","mouradabchiche01@gmail.com"),
    ("Farouk","ADDA","MCB","farouk.adda@usthb.edu.dz"),
    ("Aldjia","AIDER","MAA","aider_aldjia@hotmail.com"),
    ("Yacine","AIT AMRANE","PROF","yacinait@gmail.com"),
    ("Sofiane Abdelhamid","ATMANI","MCB","atmani.sofiane@hotmail.com"),
    ("Aicha","BATOUL","PROF","aicha.batoul@usthb.edu.dz"),
    ("Saida","BEKHOUCHE","MAA","sbekhouche17@gmail.com"),
    ("Abdelaziz","BELLAGH","MCA","bellaghabdelaziz2016@gmail.com"),
    ("Nasreddine","BENBELKACEM","MCB","nasreddine.benbelkacem@usthb.edu.dz"),
    ("Nabil","BENNENNI","MCA","nabil.bennenni@gmail.com"),
    ("Chahrazed","BENOUARET","MCB","chahrabenoua@hotmail.com"),
    ("Boualem","BENSEBA","PROF","boualem.benseba@usthb.edu.dz"),
    ("Ilhem","BENZAOUI","MAA","ibenzaoui@mail.com"),
    ("Rachid","BOUCHENNA","MCA","rachidbouchenna@yahoo.fr"),
    ("Chahrazade","BOUYACOUB","MCB","cbouyacoub@yahoo.fr"),
    ("Redha","CHELLAL","MCB","chellal.redha@gmail.com"),
    ("Karima","DJAIB","MAA","kdjaib65@gmail.com"),
    ("Akila","DJOUMAKH","MCB","adjoumakh@yahoo.fr"),
    ("Zahia Fatma","FERNANE","MAA","fernanezahia@gmail.com"),
    ("Tarek","GARICI","MCA","tarek.garici@usthb.edu.dz"),
    ("Saida","HADDADA","MAA","benatiasaida@gmail.com"),
    ("Mohand Ouamar","HERNANE","PROF","vdpgr.maths@gmail.com"),
    ("Nora","MAHLOUL","MCB","noramahloul@yahoo.fr"),
    ("Nadia","MAMMA","MAA","nadia.mamma@yahoo.fr"),
    ("Youcef","MAOUCHE","MCA","youcef.maouche@usthb.edu.dz"),
    ("Amel","MAOUCHE","MAA","ryyyma@gmail.com"),
    ("Mohamed","MECHACHA","MCB","mohamed.mechacha@gmail.com"),
    ("Rachida","MOUHOUB","MAA","mouhoub636@gmail.com"),
    ("Razika","NIBOUCHA","MCB","niboucha_razika@yahoo.fr"),
    ("Med-Salem","REZAOUI","PROF","s_rezaoui@yahoo.fr"),
    ("Schehrazad","SELMANE","PROF","scselmane@yahoo.fr"),
    ("Fadhila","SIAHMED","MAB","siahmedfadila6@gmail.com"),
    ("Leila Schehrazade","ZERROUKHAT","MCB","szerroukhat@yahoo.fr"),
    ("Nouara","ZOUBIR","MAA","znznouara42@gmail.com"),
]

# Dept Analyse (extrait de fmath.usthb.dz)
ana = [
    ("Soraya","ABDELAZIZ","MCB","sorayaabd2@gmail.com"),
    ("Mahdi","ABID","MCA","m_abid_99@yahoo.fr"),
    ("Naas","ADJIMI","MCB","naasadjimi@gmail.com"),
    ("Fatah","AGGOUNE","MCB","agg-fatah@hotmail.com"),
    ("Mohammed","AILI","MCA","mohammed.aili@usthb.edu.dz"),
    ("Abdelhamid","AINOUZ","MCB","ainouz@gmail.com"),
    ("Naima","AISSA","PROF","aissa.naima@gmail.com"),
    ("Tarik","ALIZIANE","PROF","taliziane@gmail.com"),
    ("Malika","AMIR","MAA","a_malika07@yahoo.fr"),
    ("Ali","ASSEM","MCB","albimaf@yahoo.fr"),
    ("Aldjia","ATTALLAH","MCB","attallahwarda@gmail.com"),
    ("Abdelkhalek","BALEHOUANE","MCB","abdelkhalek.balehouane@usthb.edu.dz"),
    ("Samir","BEDROUNI","MCA","sbedrouni@usthb.dz"),
    ("Abdelhakim Tarik","BELGHAZI","MCB","hbelghazi@yahoo.fr"),
    ("Mehdi","BELRAOUTI","MCA","mehdi.belraouti@gmail.com"),
    ("Imen","BENABBAS","MCA","benabbas.im@gmail.com"),
    ("Abdelkader","BENABIDALLAH","MCA","a_benabidallah@yahoo.fr"),
    ("Ahlem","BENRAOUDA","MCA","benraouda.ahlem@gmail.com"),
    ("Tounsia","BENZEKRI","PROF","toubenzekri@gmail.com"),
    ("Samira","BEYOUD","MCB","formathematic@gmail.com"),
    ("Sara","BIOUT","MAA","srbiout@gmail.com"),
    ("Rachida","BOUDJERADA","MCA","ra.boudjerada@gmail.com"),
    ("Amira","BOUGHOUFALA","MCB","boughoufalaamira000@gmail.com"),
    ("Aissa","BOUKAROU","MCB","boukarouaissa@gmail.com"),
    ("Habiba","BOULAIKI","MCA","habiba_boulaiki@yahoo.fr"),
    ("Hizia","BOUNADJA","MCB","hiziabounadja2@gmail.com"),
    ("Radia","BOURAOUI","MAA","bouraouiradia2@gmail.com"),
    ("Khaled El Ghaouti","BOUTARENE","MCA","boutarenekhaled@yahoo.fr"),
    ("Aicha","CHAOUI","MAA","chaoui_aicha2000@yahoo.fr"),
    ("Aicha","CHAREF KHODJA","MAA","acharefkhodja@yahoo.com"),
    ("Souad","CHENTOUT","MAA","chentout@yahoo.fr"),
    ("Djamel Eddine","CHERIET","MAA","dcheriet@usthb.dz"),
    ("Ouahiba","CHERIKH","MAA","ouahiba_cherikh@yahoo.fr"),
    ("Dahira","DALI","MCA","dddahira@gmail.com"),
    ("Mohamed","DEFFAF","MCB","m.deffaf@gmail.com"),
    ("Nadjiba","FOUKROUN","MCA","nfoukroun@gmail.com"),
    ("Nardjes","GASMI","MAA","nardjesgasmi11951@gmail.com"),
    ("Takoua","HAFSI","MCB","h.takamer5@gmail.com"),
    ("Noureddine","HANNOUN","MCA","nhannoun@usthb.dz"),
    ("Anis","HEZZAM","MCB","anis.hezzam@usthb.edu.dz"),
    ("Hichem","KASRI","MCA","h.kasri@hotmail.com"),
    ("M'hamed","KESRI","PROF","mkes33dz@yahoo.fr"),
    ("Arezki","KESSI","PROF","arkessi@yahoo.com"),
    ("Sofiane","KHOUTIR","MCA","khoutir.math@gmail.com"),
    ("Toufik","LAADJ","PROF","laadjt@gmail.com"),
    ("Adel","LACHOURI","MCB","lachouri.adel@yahoo.fr"),
    ("Samia","LAKHAL","MAA","slakhal65@gmail.com"),
    ("Khaled","M'HAMED-MESSAOUD","MCA","KMhamedMessaoud@gmail.com"),
    ("Abdelouahab","MAHMOUDI","MCB","aomahmoudi@yahoo.fr"),
    ("Sihem","MAHOUI","MCA","sihem.mahoui@usthb.edu.dz"),
    ("Mohammed","MEDJDEN","PROF","mmedjden@yahoo.fr"),
    ("Sana","MERZOUGUI","MAA","souhane1982@gmail.com"),
    ("Chahrazed","MEZOUED","MAA","ch_mezoued@yahoo.fr"),
    ("Zaina","NEMMAR","MAA","z.nemmar1@gmail.com"),
    ("Walid","OUKIL","MCA","woukil@usthb.dz"),
    ("Malika","OUSSALAH","MCB","oussalah_m@yahoo.fr"),
    ("Hadjer","OUZZANE","MCB","hadjer.ouzzane7@gmail.com"),
    ("Said Yazid","RAFFED","MCB","ysraffed@gmail.com"),
    ("Dirar","REBAH","PROF","dirarbath@yahoo.co.uk"),
    ("Samira","RIHANI","MCB","maths_samdz@yahoo.fr"),
    ("Fatiha","SAADALLAH","MAA","saadallah.fatiha@gmail.com"),
    ("Lamia","SEGHOUR","MCA","seghour.lamia@gmail.com"),
    ("Messaoud","SOUILAH","MCA","msouilah@gmail.com"),
    ("Fatima Zahra","TANI","MCB","tani.fatimazahra@gmail.com"),
    ("Leila","TERFASSE","MAA","l.sebaa2016@gmail.com"),
    ("Arezki","TOUZALINE","PROF","touzalinearezki214@gmail.com"),
    ("Moussa","YAHI","MCB","moussa-yahi@hotmail.fr"),
    ("Nawel","ZAIDI","MAA","zaidinawel@gmail.com"),
    ("Youcef","ZIAD","MAA","z.youcef89@yahoo.fr"),
]

# ---- FACULTE DE PHYSIQUE ----
phys_ray = [
    ("Mohamed","ALLAB","PROF","m.allab@usthb.dz"),
    ("Amar","AMOKRANE","PROF","amokrane@usthb.dz"),
    ("Fatima","BENAMARA","MCA","f.benamara@usthb.dz"),
    ("Noureddine","BENHARRATS","PROF","n.benharrats@usthb.dz"),
    ("Dalila","BENSAID","MCA","d.bensaid@usthb.dz"),
    ("Yasmina","BOUDISSA","MCB","y.boudissa@usthb.dz"),
    ("Leila","BOUSSOUF","MCA","l.boussouf@usthb.dz"),
    ("Hocine","DERRAR","MCA","h.derrar@usthb.dz"),
    ("Fatiha","DJAFRI","MAA","f.djafri@usthb.dz"),
    ("Abdelkrim","FEKRACHE","MCA","a.fekrache@usthb.dz"),
    ("Mohammed","GRAINE","MCA","m.graine@usthb.dz"),
    ("Nassima","GUETTAF","MAA","n.guettaf@usthb.dz"),
    ("Samir","HANNANE","MCB","s.hannane@usthb.dz"),
    ("Malika","HOCINE","MCA","m.hocine@usthb.dz"),
    ("Zineb","KESSI","MAA","z.kessi@usthb.dz"),
    ("Mohamed","LAMROUS","PROF","m.lamrous@usthb.dz"),
    ("Hamid","MANSOURI","PROF","h.mansouri@usthb.dz"),
    ("Nadia","OUKRIF","MCB","n.oukrif@usthb.dz"),
    ("Hafida","RAHMOUN","MCA","h.rahmoun@usthb.dz"),
    ("Abderrahmane","SEGHOUR","MCA","a.seghour@usthb.dz"),
    ("Mokhtar","TAZROUT","MCB","m.tazrout@usthb.dz"),
    ("Souad","ZERROUKI","MCA","s.zerrouki@usthb.dz"),
]

phys_mat = [
    ("Hamid","AMAR","PROF","h.amar@usthb.dz"),
    ("Djilali","BENSAID","PROF","dj.bensaid@usthb.dz"),
    ("Rachid","BOUGRIOUA","MCA","r.bougrioua@usthb.dz"),
    ("Said","DAOUD","PROF","s.daoud@usthb.dz"),
    ("Abdelkader","DEKKAR","MCB","a.dekkar@usthb.dz"),
    ("Saida","GOUMIRI","MCA","s.goumiri@usthb.dz"),
    ("Nasser","GUERMAT","MCA","n.guermat@usthb.dz"),
    ("Rachida","GUETTAF","MAA","r.guettaf@usthb.dz"),
    ("Salima","HAMZA","MCB","s.hamza@usthb.dz"),
    ("Arezki","IZERROUKEN","PROF","a.izerrouken@usthb.dz"),
    ("Abdelkrim","KEFFOUS","PROF","a.keffous@usthb.dz"),
    ("Azzeddine","KHELFANE","MCA","a.khelfane@usthb.dz"),
    ("Tahar","LAOUI","PROF","t.laoui@usthb.dz"),
    ("Hocine","MERADJI","PROF","h.meradji@usthb.dz"),
    ("Nadia","MEZAOUI","MAA","n.mezaoui@usthb.dz"),
    ("Fatiha","MOULAI-KHATIR","MCA","f.moulaikhatir@usthb.dz"),
    ("Kaddour","RAHMOUN","PROF","k.rahmoun@usthb.dz"),
    ("Nour Eddine","SARI","PROF","ne.sari@usthb.dz"),
    ("Abdelghani","SOUDANI","MCA","a.soudani@usthb.dz"),
    ("Mustapha","TABET","PROF","m.tabet@usthb.dz"),
]

phys_ener = [
    ("Rabah","BENNACER","PROF","r.bennacer@usthb.dz"),
    ("Kamel","BENDERRADJI","MCA","k.benderradji@usthb.dz"),
    ("Noureddine","BENHARRATS","PROF","n.benharrats@usthb.dz"),
    ("Samir","BENISSAD","MCB","s.benissad@usthb.dz"),
    ("Fatiha","BOUAZIZ","MCA","f.bouaziz@usthb.dz"),
    ("Ali","HADJADJ","PROF","a.hadjadj@usthb.dz"),
    ("Malika","HENICHE","MCB","m.heniche@usthb.dz"),
    ("Amina","KADDOURI","MAA","a.kaddouri@usthb.dz"),
    ("Smail","KHALFALLAH","PROF","s.khalfallah@usthb.dz"),
    ("Rafik","KHELFAOUI","MCA","r.khelfaoui@usthb.dz"),
    ("Zahia","LEILA","MAA","z.leila@usthb.dz"),
    ("Dalila","MAHDI","MCB","d.mahdi@usthb.dz"),
    ("Omar","RAHLI","PROF","o.rahli@usthb.dz"),
    ("Noureddine","SAIDANE","PROF","n.saidane@usthb.dz"),
    ("Mohamed","SALHI","MCA","m.salhi@usthb.dz"),
    ("Azzedine","SMAILI","MCB","a.smaili@usthb.dz"),
    ("Naima","ZERAIBI","PROF","n.zeraibi@usthb.dz"),
]

phys_theo = [
    ("Lamine","BENKHALED","MCA","l.benkhaled@usthb.dz"),
    ("Noureddine","BOUARISSA","PROF","n.bouarissa@usthb.dz"),
    ("Fouad","BRAHIM BELHAOUARI","MCB","f.brahimbelhaouari@usthb.dz"),
    ("Mohamed","CHAMI","PROF","m.chami@usthb.dz"),
    ("Abdelkarim","CHERIFI","MCA","a.cherifi@usthb.dz"),
    ("Fatiha","DJAMA","MAA","f.djama@usthb.dz"),
    ("Rabah","GUERROUDJI","PROF","r.guerroudji@usthb.dz"),
    ("Amel","HAMIDOUCHE","MCB","a.hamidouche@usthb.dz"),
    ("Mohamed","KHODJA","PROF","m.khodja@usthb.dz"),
    ("Dalila","MESRI","MAA","d.mesri@usthb.dz"),
    ("Bouchra","MOKHTARI","MCB","b.mokhtari@usthb.dz"),
    ("Nadia","RAMDANE","MCA","n.ramdane@usthb.dz"),
    ("Mostefa","RAHMOUNE","PROF","m.rahmoune@usthb.dz"),
    ("Ahmed","ZERARKA","PROF","a.zerarka@usthb.dz"),
]

# ---- FACULTE DE CHIMIE ----
chimie = [
    # Chimie Organique AppliquEe
    ("Nacera","ACHOUR","MCA","n.achour@usthb.dz"),
    ("Fatima Zohra","BENKARA MOSTEFA","PROF","fz.benkaramostefa@usthb.dz"),
    ("Amel","BOUASLA","MCB","a.bouasla@usthb.dz"),
    ("Leila","BOUCHEMMA","MCA","l.bouchemma@usthb.dz"),
    ("Samira","BOUKHORS","MCB","s.boukhors@usthb.dz"),
    ("Wafa","CHEKAL","MAA","w.chekal@usthb.dz"),
    ("Safia","DERKAOUI","MCA","s.derkaoui@usthb.dz"),
    ("Hakima","FERHAT","MCB","h.ferhat@usthb.dz"),
    ("Malika","HADDAD","PROF","m.haddad@usthb.dz"),
    ("Nawal","KHALDI","MAA","n.khaldi@usthb.dz"),
    ("Faiza","LAMARI","MCA","f.lamari@usthb.dz"),
    ("Chahira","MEBARKI","MCB","c.mebarki@usthb.dz"),
    ("Saida","MEKLATI","PROF","s.meklati@usthb.dz"),
    ("Fouzia","MERABET","MCA","f.merabet@usthb.dz"),
    ("Nadia","MOSTEFAOUI","MAA","n.mostefaoui@usthb.dz"),
    ("Djaouida","SAIDI","MCB","dj.saidi@usthb.dz"),
    ("Houria","TOUMI","PROF","h.toumi@usthb.dz"),
    ("Karima","YOUS","MCA","k.yous@usthb.dz"),
    # Chimie Physique et ThEorique
    ("Abdelkader","BENCHETTARA","PROF","a.benchettara@usthb.dz"),
    ("Samir","BENSEGUENI","MCA","s.bensegueni@usthb.dz"),
    ("Abdelkrim","CHERIFI","MCA","a.cherifi@fchimie.usthb.dz"),
    ("Rachida","DOUFNOUNE","PROF","r.doufnoune@usthb.dz"),
    ("Hamid","GRIB","PROF","h.grib@usthb.dz"),
    ("Kamel","GUERROUDJ","MCB","k.guerroudj@usthb.dz"),
    ("Sonia","LEKMINE","MAA","s.lekmine@usthb.dz"),
    ("Djamal","MEZIANI","MCA","dj.meziani@usthb.dz"),
    ("Naima","REZGUI","PROF","n.rezgui@usthb.dz"),
    ("Aicha","SEDDIKI","MCB","a.seddiki@usthb.dz"),
    # Chimie MacromolEculaire
    ("Rachid","AMMAR","MCA","r.ammar@usthb.dz"),
    ("Nacera","BELKEBIR","PROF","n.belkebir@usthb.dz"),
    ("Nadia","BENBAKHTI","MCA","n.benbakhti@usthb.dz"),
    ("Fatima","BOUZIT","MAA","f.bouzit@usthb.dz"),
    ("Boubaker","DAHMANI","MCB","b.dahmani@usthb.dz"),
    ("Sihem","DERBAL","MCA","s.derbal@usthb.dz"),
    ("Djaffar","HAMADOUCHE","PROF","dj.hamadouche@usthb.dz"),
    ("Nacereddine","HADDAOUI","PROF","n.haddaoui@usthb.dz"),
    ("Amel","MANSERI","MCB","a.manseri@usthb.dz"),
    ("Farida","MOKHTARI","MCA","f.mokhtari@usthb.dz"),
    ("Mouloud","OULD KADA","PROF","m.ouldkada@usthb.dz"),
    ("Abdelkader","TALBI","MCB","a.talbi@usthb.dz"),
    # Chimie et Physique des MatEriaux Inorganiques
    ("Hafida","AISSAOUI","MCB","h.aissaoui@usthb.dz"),
    ("Noura","AOUDJIT","MAA","n.aoudjit@usthb.dz"),
    ("Mohamed","BENBOUZID","PROF","m.benbouzid@usthb.dz"),
    ("Riad","BENNACER","MCA","r.bennacer@usthb.dz"),
    ("Karima","BOUDJENANE","MCA","k.boudjenane@usthb.dz"),
    ("Samira","BOUHEDADJA","MCB","s.bouhedadja@usthb.dz"),
    ("Farouk","BOUKRIF","PROF","f.boukrif@usthb.dz"),
    ("Zahia","CHAIBI","MCA","z.chaibi@usthb.dz"),
    ("Lydia","GUERBOUS","MCB","l.guerbous@usthb.dz"),
    ("Abdellah","LOUNIS","PROF","a.lounis@usthb.dz"),
    ("Fatima","MELLAH","MCA","f.mellah@usthb.dz"),
    ("Rachida","OUALI","MCB","r.ouali@usthb.dz"),
    ("Belkacem","ZIBOUCHE","PROF","b.zibouche@usthb.dz"),
]

# ---- FACULTE D'INFORMATIQUE ----
info = [
    # Dept Intelligence Artificielle et Sciences des DonnEes
    ("Faiza","ABBACI","MCA","f.abbaci@usthb.dz"),
    ("Yazid","AITOUCHE","MCB","y.aitouche@usthb.dz"),
    ("Aicha","AMROUCHE","PROF","a.amrouche@usthb.dz"),
    ("Omar","BOUSSAID","PROF","o.boussaid@usthb.dz"),
    ("Abdelkader","BENYETTOU","PROF","a.benyettou@usthb.dz"),
    ("Fatma","BOUALI","MCA","f.bouali@usthb.dz"),
    ("Wassila","BOULAHIA CHETOUANI","PROF","w.boulahiachetouani@usthb.dz"),
    ("Abdelkarim","BOUSSAID","MCA","a.boussaid@usthb.dz"),
    ("Mohamed","CHIKHI","PROF","m.chikhi@usthb.dz"),
    ("Malika","DEBBAH","MCB","m.debbah@usthb.dz"),
    ("Souad","EMBAREK","MCA","s.embarek@usthb.dz"),
    ("Karima","FERGANE","MCB","k.fergane@usthb.dz"),
    ("Nabiha","HADJ HENNI","MCA","n.hadjhenni@usthb.dz"),
    ("Nadir","HAMAMI","PROF","n.hamami@usthb.dz"),
    ("Amel","KARKOUCH","MAA","a.karkouch@usthb.dz"),
    ("Hacene","KEDJOUR","MCB","h.kedjour@usthb.dz"),
    ("Lynda","KESSAL","MCB","l.kessal@usthb.dz"),
    ("Abderrahmane","KHIAT","MCA","a.khiat@usthb.dz"),
    ("Kamel","KHOUALDI","PROF","k.khoualdi@usthb.dz"),
    ("Abdelmalek","LECHEHEB","MCB","a.lecheheb@usthb.dz"),
    ("Kahina","MAHDI","MCA","k.mahdi@usthb.dz"),
    ("Samir","MALKI","PROF","s.malki@usthb.dz"),
    ("Tahar","MEKHAZNIA","MCB","t.mekhaznia@usthb.dz"),
    ("Abdelhamid","MELLOUK","PROF","a.mellouk@usthb.dz"),
    ("Asmaa","MOUDJARI","MAA","a.moudjari@usthb.dz"),
    ("Zoubida","OUADAH","MCA","z.ouadah@usthb.dz"),
    ("Dihia","REMMANE","MCB","d.remmane@usthb.dz"),
    ("Hassina","SERIDI","PROF","h.seridi@usthb.dz"),
    ("Amina","SERIR","PROF","a.serir@usthb.dz"),
    ("Aissa","SI LARBI","MCA","a.silarbi@usthb.dz"),
    ("Saliha","TABET AOUL","MCA","s.tabetaoul@usthb.dz"),
    ("Samia","TIGANE","MCB","s.tigane@usthb.dz"),
    ("Mohamed","YALAOUI","MCB","m.yalaoui@usthb.dz"),
    # Dept SystEmes Informatiques
    ("Amar","ABBOUSH","MCB","a.abboush@usthb.dz"),
    ("Hacene","BELBACHIR","PROF","h.belbachir@usthb.dz"),
    ("Nassim","BENAMRANE","PROF","n.benamrane@usthb.dz"),
    ("Zahira","BENSEBAA","MCB","z.bensebaa@usthb.dz"),
    ("Mohamed","BOUDJELLAL","MCA","m.boudjellal@usthb.dz"),
    ("Farid","BOUKHOBZA","MCA","f.boukhobza@usthb.dz"),
    ("Fella","BOUMEDIENNE","MCB","f.boumedienne@usthb.dz"),
    ("Lahcene","BOUSELMI","MCB","l.bouselmi@usthb.dz"),
    ("Amina","CHIBANI","PROF","a.chibani@usthb.dz"),
    ("Nawel","CHIKOUCHE","MCA","n.chikouche@usthb.dz"),
    ("Karima","DERDOUR","MAA","k.derdour@usthb.dz"),
    ("Djamal","FENAS","MCB","dj.fenas@usthb.dz"),
    ("Aissa","FLITTI","MCA","a.flitti@usthb.dz"),
    ("Riad","HADJ-SAID","MCB","r.hadjsaid@usthb.dz"),
    ("Djamel","HIDOUCI","PROF","dj.hidouci@usthb.dz"),
    ("Mohamed","KHIREDDINE","MCA","m.khireddine@usthb.dz"),
    ("Nadia","KIRAN","MCB","n.kiran@usthb.dz"),
    ("Azeddine","MAZARI","PROF","a.mazari@usthb.dz"),
    ("Saliha","MEKIBES","MCB","s.mekibes@usthb.dz"),
    ("Faiza","TITOUNA","MCA","f.titouna@usthb.dz"),
    ("Fatiha","ZAIDI","MCB","fatiha.zaidi@usthb.dz"),
]

# ---- FACULTE DE BIOLOGIE ----
bio = [
    # Ecologie et Environnement
    ("Besma","ABDELGUERFI BERREKBIA","MCA","b.abdelguerfi@usthb.dz"),
    ("Mohamed","ACHOUR","PROF","m.achour@usthb.dz"),
    ("Leila","AIT MOULOUD","MCB","l.aitmouloud@usthb.dz"),
    ("Amira","BABALI","MCB","a.babali@usthb.dz"),
    ("Abdelkrim","BENAMAR","MCA","a.benamar@usthb.dz"),
    ("Naima","BOUCHIKHI TANI","PROF","n.bouchikhitani@usthb.dz"),
    ("Amira","DALI","MCB","a.dali@usthb.dz"),
    ("Houria","DJABRI","PROF","h.djabri@usthb.dz"),
    ("Sabrina","DOUMANDJI","PROF","s.doumandji@usthb.dz"),
    ("Rachid","GRIM","MCA","r.grim@usthb.dz"),
    ("Mabrouk","HAMROUCHE","PROF","m.hamrouche@usthb.dz"),
    ("Hayat","HADJOUDJA","MCB","h.hadjoudja@usthb.dz"),
    ("Hafida","KHENCHOUCHE","MCA","h.khenchouche@usthb.dz"),
    ("Rachid","MEDDOUR","PROF","r.meddour@usthb.dz"),
    ("Farida","MEFTI KORTBI","MCA","f.meftikortbi@usthb.dz"),
    ("Selma","NAIT MAZI","MCB","s.naitmazi@usthb.dz"),
    ("Wahiba","OUAFI","MAA","w.ouafi@usthb.dz"),
    ("Meriem","SEMMAR","MCA","m.semmar@usthb.dz"),
    ("Nora","SOUAT","MAA","n.souat@usthb.dz"),
    ("Karima","TERKI HASSAINE","MCB","k.terkihassaine@usthb.dz"),
    ("Imene","ZERROUKI","MAA","i.zerrouki@usthb.dz"),
    # Biologie Cellulaire et MolEculaire
    ("Meriem","AIMEUR","MCB","m.aimeur@usthb.dz"),
    ("Karima","AIT ABDELOUAHAB","MCA","k.aitabdelouahab@usthb.dz"),
    ("Naima","BENHASSINE","PROF","n.benhassine@usthb.dz"),
    ("Hafida","BENSAADI","PROF","h.bensaadi@usthb.dz"),
    ("Nabila","BENMANSOUR","MCA","n.benmansour@usthb.dz"),
    ("Fatima","BERKANE","MCB","f.berkane@usthb.dz"),
    ("Rachid","BOUCHEKER","MCB","r.boucheker@usthb.dz"),
    ("Amina","CHALLAL","MCA","a.challal@usthb.dz"),
    ("Fouzia","DERARDJA","MCB","f.derardja@usthb.dz"),
    ("Yasmina","DJOUDI","MAA","y.djoudi@usthb.dz"),
    ("Aicha","FERHAT","PROF","a.ferhat@fbiol.usthb.dz"),
    ("Farida","KEDAD","MCA","f.kedad@usthb.dz"),
    ("Farida","LAHOUEL","PROF","f.lahouel@usthb.dz"),
    ("Radia","LAIB","MCB","r.laib@usthb.dz"),
    ("Samia","LOUHIBI","MCA","s.louhibi@usthb.dz"),
    ("Assia","MERZOUK","PROF","a.merzouk@usthb.dz"),
    ("Nawel","OUADAH","MCB","n.ouadah@usthb.dz"),
    ("Siham","RAHMANI","MCA","s.rahmani@usthb.dz"),
    ("Smain","SAHRAOUI","PROF","s.sahraoui@usthb.dz"),
    ("Mounia","SAIDJI","MCB","m.saidji@usthb.dz"),
    # Biologie et Physiologie des Organismes
    ("Samira","AISSI","MCB","s.aissi@usthb.dz"),
    ("Malika","AKACHA","MCA","m.akacha@usthb.dz"),
    ("Safia","ARKOUB","MAA","s.arkoub@usthb.dz"),
    ("Houria","BENSEKHRIA","MCA","h.bensekhria@usthb.dz"),
    ("Hacina","BENTOUATI","PROF","h.bentouati@usthb.dz"),
    ("Fouzia","BOUDJENAH","MCB","f.boudjenah@usthb.dz"),
    ("Abdelmalek","BOULAHBEL","MCA","a.boulahbel@usthb.dz"),
    ("Zohra","DIAF","MAA","z.diaf@usthb.dz"),
    ("Soumia","HAMDI","MCB","s.hamdi@usthb.dz"),
    ("Chafia","KACED","MCB","c.kaced@usthb.dz"),
    ("Nadira","KALLEL","MAA","n.kallel@usthb.dz"),
    ("Samira","LARINOUNA","MCB","s.larinouna@usthb.dz"),
    ("Farouk","MENOUAR","MCA","f.menouar@usthb.dz"),
    ("Tarek","MEZIANE","MCB","t.meziane@usthb.dz"),
    ("Amel","OUALI","MCB","a.ouali@usthb.dz"),
    ("Nawel","REGUIEG","MAA","n.reguieg@usthb.dz"),
    ("Houria","SMAIL SAADOUN","PROF","h.smailsaadoun@usthb.dz"),
    ("Farida","TOUAIBIA","PROF","f.touaibia@usthb.dz"),
]

# ---- FACULTE DE GENIE CIVIL ----
gc = [
    # Dept Structures et MatEriaux
    ("Abderrahmane","ADOUM","MCA","a.adoum@usthb.dz"),
    ("Mohamed Salah","AGGOUN","PROF","ms.aggoun@usthb.dz"),
    ("Mustapha","AIT IDER","MCB","m.aitider@usthb.dz"),
    ("Noureddine","AMROUNE","PROF","n.amroune@usthb.dz"),
    ("Fouad","BELARBI","PROF","f.belarbi@usthb.dz"),
    ("Sabeur","BELE","MCA","s.bele@usthb.dz"),
    ("Ahmed","BENIDIR","MCB","a.benidir@usthb.dz"),
    ("Lakhdar","BENYAHIA","PROF","l.benyahia@usthb.dz"),
    ("Mohamed","BOUHICHA","PROF","m.bouhicha@usthb.dz"),
    ("Karim","BOUZID","MCA","k.bouzid@usthb.dz"),
    ("Tahar","BOUZIANI","PROF","t.bouziani@usthb.dz"),
    ("Farid","DEBIEB","PROF","f.debieb@usthb.dz"),
    ("Toufik","GALAI","MCB","t.galai@usthb.dz"),
    ("Rachid","HANINI","PROF","r.hanini@usthb.dz"),
    ("Mohamed","HAOUAM","MCB","m.haouam@usthb.dz"),
    ("Hassen","HENTIT","MCA","h.hentit@usthb.dz"),
    ("Sofiane","KENAI","PROF","s.kenai@usthb.dz"),
    ("Nadjib","LAOUAR","MCA","n.laouar@usthb.dz"),
    ("Amar","LEFILEF","MCB","a.lefilef@usthb.dz"),
    ("Nabil","LOUNIS","PROF","n.lounis@usthb.dz"),
    ("Nasser","MANSOUR","MCB","n.mansour@usthb.dz"),
    ("Mohammed","MOULI","PROF","m.mouli@usthb.dz"),
    ("Djamel","OUSSEDIK","MCA","dj.oussedik@usthb.dz"),
    ("Amar","SLIMANI","PROF","a.slimani@usthb.dz"),
    ("Said","TAZROUT","MCA","s.tazrout@usthb.dz"),
    ("Abdelmadjid","ZAIDI","PROF","a.zaidi@usthb.dz"),
    # Dept GEotechnique et Hydraulique
    ("Mebrouk","BELGACEM","MCA","m.belgacem@usthb.dz"),
    ("Abdelkader","BENAMAR","PROF","a.benamar@fgc.usthb.dz"),
    ("Djamel","BERBER","MCB","dj.berber@usthb.dz"),
    ("Oulaid","BOUZID","PROF","o.bouzid@usthb.dz"),
    ("Messaoud","DERGAL","MCA","m.dergal@usthb.dz"),
    ("Arezki","DJEMILI","PROF","a.djemili@usthb.dz"),
    ("Amel","GUETTACHE","MCB","a.guettache@usthb.dz"),
    ("Cherif","HARRAT","MCA","c.harrat@usthb.dz"),
    ("Mohand Said","KACIMI","PROF","ms.kacimi@usthb.dz"),
    ("Khaled","KHERICI","MCB","k.kherici@usthb.dz"),
    ("Salah","LAROUCI","PROF","s.larouci@usthb.dz"),
    ("Abdelkrim","MEKKI","MCA","a.mekki@usthb.dz"),
    ("Rezk","OURICI","MCB","r.ourici@usthb.dz"),
    ("Fella","RABEHI","MCB","f.rabehi@usthb.dz"),
    ("Nadir","SALHI","MCA","n.salhi@usthb.dz"),
    ("Noureddine","SMAIL","PROF","n.smail@usthb.dz"),
    ("Azzedine","TAGELDIN","MCB","a.tageldin@usthb.dz"),
    ("Zineb","ZIANI","MAA","z.ziani@usthb.dz"),
]

# ---- FACULTE DE GENIE ELECTRIQUE ----
elec = [
    # Electronique
    ("Hakim","ACHOUR","MCA","h.achour@usthb.dz"),
    ("Abdenour","AISSAOUI","PROF","a.aissaoui@usthb.dz"),
    ("Amina","AISSOU","MCB","a.aissou@usthb.dz"),
    ("Ferhat","BETTAYEB","PROF","f.bettayeb@usthb.dz"),
    ("Tarek","BOULMEZAOUD","MCB","t.boulmezaoud@usthb.dz"),
    ("Lamine","BOUNOUA","MCA","l.bounoua@usthb.dz"),
    ("Hakim","DEGHICHE","MCB","h.deghiche@usthb.dz"),
    ("Nadia","DJEBBOURI","MCA","n.djebbouri@usthb.dz"),
    ("Habiba","GHARBI","PROF","h.gharbi@usthb.dz"),
    ("Mourad","GOUGAM","MCA","m.gougam@usthb.dz"),
    ("Cherif","GUERRACHE","MCB","c.guerrache@usthb.dz"),
    ("Mohamed","KHALDI","PROF","m.khaldi@usthb.dz"),
    ("Rabah","KHEMLICHE","PROF","r.khemliche@usthb.dz"),
    ("Said","LABIOD","PROF","s.labiod@usthb.dz"),
    ("Riad","LAREDJ","MCB","r.laredj@usthb.dz"),
    ("Fatiha","LEKMINE","MCA","f.lekmine@usthb.dz"),
    ("Abdelkrim","MEKHILEF","PROF","a.mekhilef@usthb.dz"),
    ("Tahar","MEKHILEF","MCA","t.mekhilef@usthb.dz"),
    ("Rachid","MELLAH","MCA","r.mellah@usthb.dz"),
    ("Ahmed","OUAMRANE","MCB","a.ouamrane@usthb.dz"),
    ("Meriem","OUCHEN","MCB","m.ouchen@usthb.dz"),
    ("Noureddine","SBETA","MCB","n.sbeta@usthb.dz"),
    ("Badr Eddine","SEGHIER","MCA","be.seghier@usthb.dz"),
    ("Rafik","TALEB","PROF","r.taleb@usthb.dz"),
    ("Amina","ZEROUALI","MCB","a.zerouali@usthb.dz"),
    # Electrotechnique
    ("Abdelkader","AIT HELLAL","PROF","a.aithellal@usthb.dz"),
    ("Atika","BOUDISSA","MCB","a.boudissa@usthb.dz"),
    ("Said","CHERGUI","MCA","s.chergui@usthb.dz"),
    ("Amar","DEBOUCHA","PROF","a.deboucha@usthb.dz"),
    ("Badreddine","GASMI","MCA","b.gasmi@usthb.dz"),
    ("Hachemi","HAMDI","PROF","h.hamdi@usthb.dz"),
    ("Faouzi","HAMOUDI","MCB","f.hamoudi@usthb.dz"),
    ("Hadj","HOCINI","PROF","h.hocini@usthb.dz"),
    ("Farouk","LAOUFI","MCA","f.laoufi@usthb.dz"),
    ("Abdelkrim","MOUSSAOUI","MCB","a.moussaoui@usthb.dz"),
    ("Zoubida","OULD LACHEMI","PROF","z.ouldlachemi@usthb.dz"),
    ("Said","YAKOUBI","MCA","s.yakoubi@usthb.dz"),
    ("Kamila","ZERHOUNI","MCB","k.zerhouni@usthb.dz"),
    # TElEcommunications
    ("Ammar","ALIOUAT","PROF","a.aliouat@usthb.dz"),
    ("Farouk","BENMOUSSA","MCB","f.benmoussa@usthb.dz"),
    ("Youcef","BENMOUSSA","MCA","y.benmoussa@usthb.dz"),
    ("Maamar","DEBBACHE","PROF","m.debbache@usthb.dz"),
    ("Ratiba","DJEBBOURI","PROF","r.djebbouri@usthb.dz"),
    ("Amar","HADJ-HADJ","MCA","a.hadjhadj@usthb.dz"),
    ("Naceur","HENNI","MCB","n.henni@usthb.dz"),
    ("Fatiha","IBRIR","PROF","f.ibrir@usthb.dz"),
    ("Djamal","LAZREG","MCA","dj.lazreg@usthb.dz"),
    ("Karima","MEZRAG","MCB","k.mezrag@usthb.dz"),
    ("Samir","SACI","PROF","s.saci@usthb.dz"),
    ("Kamel","ZIDANI","MCA","k.zidani@usthb.dz"),
    # Automatique
    ("Aziz","BERKANI","PROF","a.berkani@usthb.dz"),
    ("Toufik","BOUDISSA","MCA","t.boudissa@usthb.dz"),
    ("Lyes","CHITER","MCB","l.chiter@usthb.dz"),
    ("Djamel","DHAHRI","PROF","dj.dhahri@usthb.dz"),
    ("Nadjib","DRICI DJEBBAR","MCB","n.dricidjebbar@usthb.dz"),
    ("Chafia","HAMDI","MCA","c.hamdi@usthb.dz"),
    ("Khatir","KHETTAB","PROF","k.khettab@usthb.dz"),
    ("Houria","KHELOUFI","MCA","h.kheloufi@usthb.dz"),
    ("Fouad","LAZHAR","MCB","f.lazhar@usthb.dz"),
    ("Abdelhalim","MEDDAHI","PROF","a.meddahi@usthb.dz"),
    ("Farida","MEZIANE","MCA","f.meziane@usthb.dz"),
    ("Abdelouahab","MEZIANE","PROF","a.meziane@usthb.dz"),
    ("Tayeb","MOHAMMEDI","MCB","t.mohammedi@usthb.dz"),
    ("Khadidja","MOURAD CHIKH","MCB","k.mouradchikh@usthb.dz"),
    ("Nawel","SEDDIK","MCA","n.seddik@usthb.dz"),
    ("Hamid","TAIBI","PROF","h.taibi@usthb.dz"),
]

# ---- FACULTE DE GENIE MECANIQUE ET PROCEDES ----
gm = [
    # Construction MEcanique et Productique
    ("Mourad","ABDELOUAHED","MCB","m.abdelouahed@usthb.dz"),
    ("Rachid","ABDELDJEBAR","MCA","r.abdeldjebar@usthb.dz"),
    ("Mustapha","BOUGHAZI","PROF","m.boughazi@usthb.dz"),
    ("Nabil","BOUKTIT","MCB","n.bouktit@usthb.dz"),
    ("Djamel","CHAOUCH","MCA","dj.chaouch@usthb.dz"),
    ("Walid","CHERIF","MCB","w.cherif@usthb.dz"),
    ("Amar","DJEBIRET","PROF","a.djebiret@usthb.dz"),
    ("Lakhdar","DJEMAI","MCA","l.djemai@usthb.dz"),
    ("Farid","ERKEK","MCB","f.erkek@usthb.dz"),
    ("Abdelhamid","GHENAIET","PROF","a.ghenaiet@usthb.dz"),
    ("Rachid","GUERRAICHE","MCB","r.guerraiche@usthb.dz"),
    ("Abdelkader","KELLOU","PROF","a.kellou@usthb.dz"),
    ("Mouad","LAMRI","MCB","m.lamri@usthb.dz"),
    ("Azzedine","LOUSDAD","PROF","a.lousdad@usthb.dz"),
    ("Mohieddine","MAKHLOUF","MCA","m.makhlouf@usthb.dz"),
    ("Driss","MEHDI","PROF","d.mehdi@usthb.dz"),
    ("Saad","MEKHILEF","MCB","s.mekhilef@usthb.dz"),
    ("Rafik","SOUAMI","MCA","r.souami@usthb.dz"),
    ("Abdelhak","TAIBI","MCB","a.taibi@usthb.dz"),
    ("Imane","TIFROUTE","MAA","i.tifroute@usthb.dz"),
    # Thermo-EnergEtique
    ("Kamal","ABBOUDI","PROF","k.abboudi@usthb.dz"),
    ("Farouk","ABED","MCB","f.abed@usthb.dz"),
    ("Mohamed","AMARA","PROF","m.amara@usthb.dz"),
    ("Fatiha","BENABDALLAH","MCA","f.benabdallah@usthb.dz"),
    ("Salah Eddine","BENISSAD","MCB","se.benissad@usthb.dz"),
    ("Lyes","BORDJI","MCA","l.bordji@usthb.dz"),
    ("Farid","CHABANE","MCB","f.chabane@usthb.dz"),
    ("Djamel","DJALAB","PROF","dj.djalab@usthb.dz"),
    ("Fatiha","LEBIED","MCB","f.lebied@usthb.dz"),
    ("Tarik","MESLEM","MCB","t.meslem@usthb.dz"),
    ("Nabil","MOUMMI","PROF","n.moummi@usthb.dz"),
    ("Farouk","REDJEM","MCB","f.redjem@usthb.dz"),
    ("Abdelkrim","SENGOUGA","PROF","a.sengouga@usthb.dz"),
    ("Abdelaziz","TOUATI","PROF","a.touati@usthb.dz"),
    ("Djelloul","YOUNSI","PROF","dj.younsi@usthb.dz"),
    # Science des MatEriaux
    ("Halima","AISSOU","MCB","h.aissou@usthb.dz"),
    ("Abdelkader","AIT FERHAT","MCA","a.aitferhat@usthb.dz"),
    ("Nacer","BACHA","PROF","n.bacha@usthb.dz"),
    ("Imane","BENALI","MCB","i.benali@usthb.dz"),
    ("Mourad","BENZERARA","MCA","m.benzerara@usthb.dz"),
    ("Hafid","BILANI","MCB","h.bilani@usthb.dz"),
    ("Hamid","DJEBAILI","PROF","h.djebaili@usthb.dz"),
    ("Azzedine","ELMOSSOUESS","MCB","a.elmossouess@usthb.dz"),
    ("Abdelkrim","HADDAD","MCA","a.haddad@usthb.dz"),
    ("Faouzi","HIDOUSSI","MCB","f.hidoussi@usthb.dz"),
    ("Lakhdar","IHADDADENE","PROF","l.ihaddadene@usthb.dz"),
    ("Fateh","LAREDJ","MCA","f.laredj@usthb.dz"),
    ("Nour Eddine","MASSINISSA","MCB","ne.massinissa@usthb.dz"),
    ("Fatiha","MEGHNI","MCB","f.meghni@usthb.dz"),
    ("Oumelkheir","SAIDAT","PROF","o.saidat@usthb.dz"),
    ("Nadia","ZERROUKI","MAA","nadia.zerrouki@usthb.dz"),
    # GEnie Chimique et CryogEnie / GEnie de l'Environnement
    ("Hamid","AIT AMAR","PROF","h.aitamar@usthb.dz"),
    ("Mohamed Raouf","BENALI","MCB","mr.benali@usthb.dz"),
    ("Sihem","BENLAKHDAR","MAA","s.benlakhdar@usthb.dz"),
    ("Chafia","BENYAMINA","MCB","c.benyamina@usthb.dz"),
    ("Farid","DAHAK","PROF","f.dahak@usthb.dz"),
    ("Naima","DJEGHRI","MCB","n.djeghri@usthb.dz"),
    ("Fatima Zohra","FERRAD","MCA","fz.ferrad@usthb.dz"),
    ("Fatima","LARKI","MCB","f.larki@usthb.dz"),
    ("Amar","MANSOURI","MCA","a.mansouri@usthb.dz"),
    ("Ryma","MENIA","MAA","r.menia@usthb.dz"),
    ("Ahcen","MOKRETAR","PROF","a.mokretar@usthb.dz"),
    ("Nabila","NACER","MCB","n.nacer@usthb.dz"),
    ("Fouzia","OTMANI","MCA","f.otmani@usthb.dz"),
    ("Lynda","SAIDANE","MCB","l.saidane@usthb.dz"),
    ("Rachid","SALHI","PROF","r.salhi@usthb.dz"),
    ("Karima","SEFIANE","MCB","k.sefiane@usthb.dz"),
    ("Smail","SEMRA","PROF","s.semra@usthb.dz"),
    ("Asma","SMAHI","MCB","a.smahi@usthb.dz"),
    ("Ratiba","TIGHIOUART","MAA","r.tighiouart@usthb.dz"),
    ("Rachida","ZOULIKHA","MCB","r.zoulikha@usthb.dz"),
]

# ---- COMPETENCES PAR DEPARTEMENT ----
COMP = {
    "AlgEbre et ThEorie des Nombres": ["AlgEbre", "ThEorie des Groupes", "ThEorie des Nombres", "AlgEbre Commutative", "Combinatoire"],
    "Analyse": ["Analyse MathEmatique", "Equations aux DErivEes Partielles", "Analyse Fonctionnelle", "Topologie", "Calcul des Variations"],
    "ProbabilitEs et Statistiques": ["ProbabilitEs", "Statistiques", "Processus Stochastiques", "ModElisation Statistique", "Analyse des DonnEes"],
    "Recherche OpErationnelle": ["Optimisation", "Recherche OpErationnelle", "Aide E la DEcision", "Programmation LinEaire", "ThEorie des Graphes"],
    "Physique des Rayonnements": ["Physique NuclEaire", "Rayonnements Ionisants", "DosimEtrie", "Radioprotection", "Physique Atomique"],
    "MatEriaux et Composants": ["Science des MatEriaux", "Physique du Solide", "Semiconducteurs", "NanomatEriaux", "Cristallographie"],
    "EnergEtique et MEcanique des Fluides": ["Thermodynamique", "MEcanique des Fluides", "Transfert de Chaleur", "Energies Renouvelables", "CFD"],
    "Physique ThEorique": ["Physique ThEorique", "MEcanique Quantique", "RelativitE", "Physique des Particules", "Cosmologie"],
    "Chimie Organique AppliquEe": ["Chimie Organique", "SynthEse Organique", "Chimie des Produits Naturels", "Pharmacochimie", "Chimie Verte"],
    "Chimie Physique et ThEorique": ["Chimie Physique", "Electrochimie", "Chimie ThEorique", "ModElisation MolEculaire", "Thermochimie"],
    "Chimie MacromolEculaire": ["PolymEres", "Chimie MacromolEculaire", "MatEriaux PolymEres", "Physicochimie des MacromolEcules", "BiopolymEres"],
    "Chimie et Physique des MatEriaux Inorganiques": ["Chimie Inorganique", "MatEriaux Inorganiques", "Cristallochimie", "SynthEse Inorganique", "Chimie du Solide"],
    "Informatique E IA": ["Intelligence Artificielle", "Machine Learning", "Traitement du Langage", "Vision par Ordinateur", "Big Data"],
    "Informatique E SystEmes": ["REseaux", "SystEmes DistribuEs", "Architecture des Ordinateurs", "SystEmes EmbarquEs", "SEcuritE Informatique"],
    "Ecologie et Environnement": ["Ecologie", "Environnement", "BiodiversitE", "Gestion des Ressources Naturelles", "Botanique"],
    "Biologie Cellulaire et MolEculaire": ["Biologie Cellulaire", "Biologie MolEculaire", "GEnEtique", "Biochimie", "Microbiologie"],
    "Biologie et Physiologie des Organismes": ["Physiologie Animale", "Biologie des Organismes", "Zoologie", "Reproduction", "Neurobiologie"],
    "Structures et MatEriaux": ["GEnie Civil", "REsistance des MatEriaux", "BEton ArmE", "Calcul des Structures", "BTP"],
    "GEotechnique et Hydraulique": ["GEotechnique", "MEcanique des Sols", "Hydraulique", "Fondations", "Ouvrages Hydrauliques"],
    "Electronique": ["Electronique", "MicroElectronique", "Traitement du Signal", "Capteurs", "Circuits IntEgrEs"],
    "Electrotechnique": ["Electrotechnique", "Machines Electriques", "Electronique de Puissance", "REseaux Electriques", "Energie Electrique"],
    "TElEcommunications": ["TElEcommunications", "REseaux de Communication", "Traitement du Signal", "Radiocommunications", "Fibre Optique"],
    "Automatique": ["Automatique", "Commande des SystEmes", "Robotique", "REgulation", "SystEmes de ContrEle"],
    "Construction MEcanique et Productique": ["Construction MEcanique", "Fabrication", "CAO", "Productique", "MEcatronique"],
    "Thermo-EnergEtique": ["Thermodynamique", "Transfert Thermique", "Energies Renouvelables", "GEnie Thermique", "Combustion"],
    "Science des MatEriaux": ["Science des MatEriaux", "MEtallurgie", "Traitements de Surface", "CaractErisation des MatEriaux", "Tribologie"],
    "GEnie Chimique et ProcEdEs": ["GEnie des ProcEdEs", "OpErations Unitaires", "GEnie Chimique", "Catalyse", "GEnie de l'Environnement"],
}

def make_bio(prenom, nom, dept, grade):
    grade_str = {
        'PROF': 'Professeur', 'MCA': 'MaEtre de confErences A',
        'MCB': 'MaEtre de confErences B', 'MAA': 'MaEtre assistant A',
        'MAB': 'MaEtre assistant B', 'MABS': 'MaEtre assistant B'
    }.get(grade, grade)
    return f"{grade_str} au dEpartement de {dept} de l'USTHB."

# Map each dataset to (list, dept_name, faculte_name, grade_col_is_index, comp_key)
DATASETS = [
    (alg, "AlgEbre et ThEorie des Nombres", "MathEmatiques"),
    (ana, "Analyse", "MathEmatiques"),
    (phys_ray, "Physique des Rayonnements", "Physique"),
    (phys_mat, "MatEriaux et Composants", "Physique"),
    (phys_ener, "EnergEtique et MEcanique des Fluides", "Physique"),
    (phys_theo, "Physique ThEorique", "Physique"),
    (chimie, "Chimie", "Chimie"),
    (info, "Informatique", "Informatique"),
    (bio, "Biologie", "Sciences Biologiques"),
    (gc, "GEnie Civil", "GEnie Civil"),
    (elec, "GEnie Electrique", "GEnie Electrique"),
    (gm, "GEnie MEcanique et ProcEdEs", "GEnie MEcanique et ProcEdEs"),
]

GRADE_MAP = {
    'PROF': 'Professeur', 'MCA': 'MaEtre de ConfErences A',
    'MCB': 'MaEtre de ConfErences B', 'MAA': 'MaEtre Assistant A',
    'MAB': 'MaEtre Assistant B', 'MABS': 'MaEtre Assistant B',
}

teachers = []
next_id = 200  # start after existing

for dataset, dept, faculte in DATASETS:
    comp_list = COMP.get(dept, ["Enseignement", "Recherche", "Formation"])
    for prenom, nom, grade_code, email in dataset:
        grade = GRADE_MAP.get(grade_code, grade_code)
        nom_full = f"{prenom} {nom}"
        bio = make_bio(prenom, nom, dept, grade_code)
        teachers.append({
            "id": next_id,
            "nom": nom_full,
            "departement": dept,
            "faculte": faculte,
            "grade": grade,
            "email": email,
            "competences": comp_list[:5],
            "bio": bio,
            "projets": 0
        })
        next_id += 1

print(f"Total new teachers: {len(teachers)}")
with open('C:\\Users\\toto\\Desktop\\descipline\\ramzy\\usthb-spa\\src\\teach\\new_teachers.json', 'w', encoding='utf-8') as f:
    json.dump(teachers, f, ensure_ascii=False, indent=2)
print("Saved to new_teachers.json")

# Preview
for t in teachers[:3]:
    print(json.dumps(t, ensure_ascii=False, indent=2))